### ISSUE TITLE
Error while running code

### ISSUE THREAD

**Issue by PrachiDabholkar** [BAPostma/PostcodeAPI.Net#1]
The command "nuget pack PostcodeAPI.Net.csproj -Prop Configuration=Release" exited with code 9009.

**Comment by BAPostma** [comment]
I'm afraid this is an error code emitted by NuGet and unrelated to this particular library.

Do ensure you've built the solution correctly and VS has access to the NuGet tools. Also perform a NuGet package restore prior to building the solution and/or package.
See also [this StackOverflow](https://stackoverflow.com/questions/15097538/nuget-install-exit-code-9009) article.

Hope this helps.
