### ISSUE TITLE
JsonSerializationException on request with certain postal codes

### ISSUE THREAD

**Issue by peterdew** [BAPostma/PostcodeAPI.Net#3]
Hi, 

A request to client.GetAddress("5804XG") returns a JsonSerializationException. 

Error converting value {null} to type 'System.Int32'. Path '_embedded.addresses[4].year', line 1, position 3552.
Is this a bug? It's a valid postalcode (https://www.postcode.nl/5804XG/1-13)

**Comment by BAPostma** [comment]
Hey Peter,
This seems like a bug which I've managed to reproduce.
There is an address in the result set that lacks a 'year' property and can therefore not be deserialised into an int value-type.

Please bear with me whilst I'm looking at fixing the problem shortly.

**Comment by BAPostma** [comment]
Fixed in release 1.2. Closing issue.
